# Numerical Python의 약자

In [1]:
# 파이썬의 수치계산 및 해석의 라이브러리

In [2]:
# 배열 : '같은 자료형'의 데이터들이 연속된 형태로 구성된 자료 구조로 다량의 데이터를 '그룹'으로 관리하며 '손쉽게 계산'하기 위해 사용

In [3]:
# sqrt : square root (제곱근)
# std : standard (표준편차)

numpy 다양한 함수들
사이트 참조 : https://codetorial.net/numpy/functions/index.html

SyntaxError: invalid syntax (48101824.py, line 4)

In [ ]:
# ndarray : n-dimension
# list와 유사하게 N차원 형태로 구성이 가능
# index가 있다

### Numpy 라이브러리

- 빅데이터의 수학적, 과학적 계산을 위해 만들어진 라이브러리
- 반복문 없이 전체 데이터의 연산이 가능한 표준 수학 함수들을 제공
- ※배열 : 같은 자료형의 값들이 연속적인 형태로 구성된 자료 구조로 대량의 데이터를 그룹으로 관리하고 계산하기 위해 사용

In [5]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5]
print(list1)

In [ ]:
type(list1)

In [ ]:
arr = np.array(list1)
print(arr)

In [ ]:
type(arr)

#### 1차원 배열

In [ ]:
arr = np.array([1,2,3.5])
print(arr)

In [ ]:
arr = np.array([1,2,'야호!'])
print(arr)

In [ ]:
arr

#### 2차원 배열

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

In [ ]:
# 배열의 형태 확인 (행, 열)
arr2.shape

In [ ]:
# 배열의 요소 전체 개수
arr2.size

In [ ]:
# 배열의 데이터 타입(자료형 확인)
arr2.dtype

In [ ]:
#32는 bit를 뜻함(기계가 표현할 수 잇는 범위) -> 2^32
# int8 => 1비트당 2개의 숫자를 표현할 수 있음 = 256개 표현 가능(-128 ~127)
# int32=> -2,147,483,648 ~ 2,147,483,647

In [ ]:
# 배열의 차원 확인
arr2.ndim

In [6]:
arr3 = np.array([[[1,2,3],[3,4,5]],[[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [ ]:
print("배열의 형태 : ", arr3.shape) # 2행 3열이 2개 (개수, 행수, 열수)
print("배열의 차원 : ", arr3.ndim)
print("배열의 전체요소개수 : ", arr3.size)

In [ ]:
# 0으로 배열 생성
arr_zeros = np.zeros((3,4))
arr_zeros

In [ ]:
# 1로 배열 생성
arr_ones = np.ones((2,4,3))
arr_ones

In [ ]:
# 특정값으로 배열 생성하기
arr_full = np.full((2,5,5),2) # 5행 5열의 배열을 2로 채워준다.
arr_full

#### 다차원배열 생성에 유용한 함수
- arange함수로 배열을 생성하고 reshape함수로 배열의 형태를 바꾸보자!

In [ ]:
# 1부터 50까지 1씩 증가하는 값들로 리스트를 만들어보자
a=[]
for i in range(1,51):
    a.append(i)
print(a)

# 만든 리스트로 배열 생성
np.array(a)

In [ ]:
# 반복문을 활용하지 않고 배열 생성
arr5 = np.arange(1,51,1)
arr5

In [ ]:
# 1부터 51까지 중에서 1,11,21,31,41로 배열을 생성해보자
arr6 = np.arange(1,51,10)
arr6

In [ ]:
arr7 = np.arange(1,51,1)
arr7

In [ ]:
# reshape : 배열의 행과 열을 변경시켜주는 명령
arr7.reshape(5,10)

In [ ]:
arr7.reshape(5,11)

In [ ]:
arr7.reshape(10,5)

In [ ]:
arr7

In [ ]:
arr7 = arr7.reshape(5,10)

In [ ]:
arr7

In [ ]:
arr8 = np.array([1.2,2.3,3.4])
arr8

In [ ]:
# 배열의 자료형을 정수형으로 변경!
arr8 = np.array([1.2,2.3,3.4], dtype=np.int64)
arr8

In [ ]:
arr9 = np.array(['1','2','3'],dtype = np.int64)
arr9

#### 랜덤(난수)값 생성!

In [ ]:
arr10 = np.random.rand(2,3)
arr10

In [ ]:
# 랜덤 정수 값 출력하기!
np.random.randint(10) # 0~9까지의 10개 숫자 중에서 랜덤으로 정수 생성


In [ ]:
# 랜덤값 정수형 배열 생성하기
np.random.randint(5,size = 10)

In [ ]:
np.random.randint(5,size = (2,3))

#### array 연산

In [ ]:
arr14 = np.array([[1,2],[3,4]])
arr14

In [ ]:
arr14+ arr14

In [ ]:
list14 = [[1,2],[3,4]]
list14

In [ ]:
list14 + list14

In [ ]:
arr14 * arr14

In [ ]:
arr14 % arr14

In [ ]:
arr14 *2

### numpy 배열의 접근은 어떻게 할까?
- 리스트와 마찬가지로 인덱싱, 슬라이싱을 지원함!

#### numpy 배열 인덱싱
- 배열 중 하나의 인덱스 값에 있는 데이터를 가져오는 것

In [1]:
arr16 = np.array([[1,2,3],[4,5,6]])
arr16

NameError: name 'np' is not defined

In [2]:
arr16[0]

NameError: name 'arr16' is not defined

In [ ]:
arr16[0][1]

#### numpy 슬라이싱
- 배열의 범위를 지정하여 여러개의 데이터를 가져오는 것

In [ ]:
arr17=np.arange(10)
arr17

In [ ]:
arr17[3:8]

In [ ]:
arr17[3:8]

In [ ]:
arr18 = np.arange(50).reshape(5,10)
arr18

In [ ]:
# 0번,1번 인덱스 행의 모든 열을 출력(arr18[행의 범위, 열의 범위])
arr18[0:2,:]

In [ ]:
# 모든 행의 0번 인덱스를 출력
arr18[:,0]

In [ ]:
print(arr18[:,0])

In [ ]:
arr18[:,0:1]

In [ ]:
arr18[:,0:2]

In [ ]:
arr18[:4,:5]

In [9]:
arr19 = np.arange(18).reshape(3,6)
arr19

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
arr19[1:,1]

In [10]:
for i in range(1:):
    for j in range(2,6,2):
        arr19[i,j]

SyntaxError: invalid syntax (1557959822.py, line 1)

In [11]:
# 방법1
arr19[1:, [1,3,5]]

array([[ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
# 방법2 - 1: :2 뜻은 1부터 끝까지 증감량2만큼 뽑는다 (시작인덱스 : 끝 인덱스 : 증감량)
arr19[1:, 1: :2]

In [ ]:
arr19

In [ ]:
arr19.T

In [ ]:
# arr.T 는 전치 (TransPosition)
# 배열의 행과 열을 바꿔주는 역할